### ISSUE TITLE
MongoDB Atlas

### ISSUE THREAD

**Issue by aclark13861** [micahwierenga/sei-cc-7-project-2-issues#6]
Need help with setting up my database and .env files

error: message: 'The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.',
  name: 'MongooseError'

**Comment by micahwierenga** [comment]
It appears that there may have been two factors:

1. The url in the `.env` file didn't have the password properly rendered (this was fixed).
2. The Atlas server may have had some connectivity issues during testing since, when trying to go to the collections, nothing was showing. But those collections appeared a little bit later.
